name: Build Docker Image (SPOOF DPI)
description: Build and push Docker image for SPOOF DPI
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build:
        description: 'Build the Docker image'
        required: true
        default: true
        type: boolean
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  PLATFORMS: linux/amd64,linux/arm64/v6,linux/arm64/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/riscv64,linux/s390x
jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    if: contains(github.event.head_commit.message, '#BUILD') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up QEMU and Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}
      - name: Generate Unique Tag
        id: unique_tag
        run: |
          UNIQUE_TAG="$(date +%s)"
          echo "Generated unique tag: $UNIQUE_TAG"
          echo "unique_tag=$UNIQUE_TAG" >> $GITHUB_OUTPUT
      - name: Build and Push Multi-Arch Image (with swag + scratch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ghcr.io/bariiss/spoofdpi:v${{ steps.unique_tag.outputs.unique_tag }}
            ghcr.io/bariiss/spoofdpi:latest
          no-cache: true
          provenance: false